services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npx prisma generate && npm run dev"
    networks:
      - default
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    hostname: postgres
    env_file:
      - ./.env
    networks:
      - default
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./database/:/var/lib/postgresql/data

volumes:
  node_modules:
networks:
  # supabase_network_hackaton:
  #   external: true
  app:
    driver: bridge
    name: app
    external: true
    attachable: true