services:
  app:
    build:
      context: .
    ports:
      - "12000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
    networks:
      - default
      - supabase_network_hackaton

volumes:
  node_modules:
networks:
  supabase_network_hackaton:
    external: true